# Generated by Django 4.0.2 on 2022-02-26 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='member',
            field=models.ManyToManyField(null=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ManyToManyField(null=True, related_name='sender', to='chat.GroupName'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
