# Generated by Django 4.0.2 on 2022-02-26 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_remove_message_reciever_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('member', models.ManyToManyField(null=True, related_name='member', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('reciever', models.ManyToManyField(related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ManyToManyField(related_name='sender', to='chat.GroupName')),
            ],
        ),
    ]
