# Generated by Django 4.0.2 on 2022-02-28 14:45

from django.conf import settings
from django.db import migrations, models
import hashtag.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hashtag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('desc', models.TextField()),
                ('attachment', models.FileField(null=True, upload_to='plans/')),
                ('accept', models.ForeignKey(null=True, on_delete=hashtag.models.superuser, related_name='accept', to=settings.AUTH_USER_MODEL)),
                ('hashtag', models.ManyToManyField(related_name='hashplans', to='hashtag.Hashtag')),
                ('username', models.ForeignKey(on_delete=hashtag.models.superuser, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
