# Generated by Django 4.0.2 on 2022-03-01 10:17

from django.conf import settings
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(null=True, on_delete=users.models.superuser, related_name='followed_by', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(null=True, on_delete=users.models.superuser, related_name='follow_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
