# Generated by Django 4.0.2 on 2022-03-05 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0003_delete_follow'),
        ('users', '0004_alter_profile_bio_alter_profile_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interests',
            name='name',
        ),
        migrations.AddField(
            model_name='interests',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest_name', to='hashtag.hashtag'),
        ),
        migrations.RemoveField(
            model_name='skills',
            name='name',
        ),
        migrations.AddField(
            model_name='skills',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_name', to='hashtag.hashtag'),
        ),
    ]
