# Generated by Django 4.0.2 on 2022-03-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_interests_name_interests_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
