# Generated by Django 4.0.2 on 2022-03-05 21:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0003_delete_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_alter_profile_mobile_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hobbies',
            unique_together={('username', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='interests',
            unique_together={('username', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='skills',
            unique_together={('username', 'name')},
        ),
    ]
