# Generated by Django 4.0.2 on 2022-03-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_hobbies_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobbies',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='interests',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['-id']},
        ),
    ]
