# Generated by Django 4.0.2 on 2022-02-23 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_remove_education_username_education_username_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='username',
        ),
        migrations.AddField(
            model_name='education',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
