# Generated by Django 4.0.2 on 2022-02-23 20:09

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_education_username_education_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('name', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('username', models.ForeignKey(null=True, on_delete=api.models.superuser, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='products',
        ),
        migrations.AddField(
            model_name='catagory',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ManyToManyField(null=True, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='message',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.catagory'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(null=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.RemoveField(
            model_name='hobbies',
            name='name',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='name',
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='reciever',
            field=models.ManyToManyField(null=True, related_name='reciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ManyToManyField(null=True, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='skills',
            name='name',
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('desc', models.TextField(null=True)),
                ('attachment', models.FileField(null=True, upload_to='plans/')),
                ('accept', models.ForeignKey(null=True, on_delete=api.models.superuser, related_name='accept', to=settings.AUTH_USER_MODEL)),
                ('hashtag', models.ManyToManyField(null=True, related_name='hashplans', to='api.Hashtag')),
                ('username', models.ForeignKey(null=True, on_delete=api.models.superuser, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti', models.CharField(max_length=128, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('desc', models.TextField(null=True)),
                ('company', models.ManyToManyField(null=True, related_name='company', to=settings.AUTH_USER_MODEL)),
                ('hashtag', models.ManyToManyField(null=True, related_name='hashtag', to='api.Hashtag')),
                ('jobseaker', models.ManyToManyField(null=True, related_name='jobseaker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='hashtag',
            field=models.ManyToManyField(related_name='plans', to='api.Hashtag'),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='name',
            field=models.ManyToManyField(related_name='hobby_name', to='api.Hashtag'),
        ),
        migrations.AddField(
            model_name='interests',
            name='name',
            field=models.ManyToManyField(related_name='interest_name', to='api.Hashtag'),
        ),
        migrations.AddField(
            model_name='skills',
            name='name',
            field=models.ManyToManyField(related_name='skill_name', to='api.Hashtag'),
        ),
    ]
