# Generated by Django 4.0.2 on 2022-02-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_group_owner_remove_products_catagory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbies',
            name='name',
        ),
        migrations.AddField(
            model_name='hobbies',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hobby_name', to='api.hashtag'),
        ),
    ]
