# Generated by Django 4.0.2 on 2022-02-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_hobbies_name_hobbies_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
    ]
