# Generated by Django 4.0.2 on 2022-02-24 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='entre',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL), max_length=100),
        ),
    ]
