# Generated by Django 4.0.2 on 2022-02-24 11:33

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_alter_profile_entre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_by', models.ForeignKey(null=True, on_delete=api.models.superuser, related_name='followed_by', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(null=True, on_delete=api.models.superuser, related_name='follow_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
