# Generated by Django 4.0.2 on 2022-02-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='hashtag',
            field=models.ManyToManyField(null=True, related_name='plans', to='api.Hashtag'),
        ),
    ]
