# Generated by Django 4.0.2 on 2022-02-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_posts_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed_by',
            new_name='following',
        ),
    ]
