# Generated by Django 4.0.2 on 2022-02-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_posts_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
