# Generated by Django 4.0.2 on 2022-02-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_posts_post_date_posts_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='hashtag',
            field=models.ManyToManyField(related_name='questionhashtag', to='api.Hashtag'),
        ),
    ]
