# Generated by Django 4.0.2 on 2022-02-25 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_questions_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='follower',
            field=models.ManyToManyField(related_name='tagfollower', to=settings.AUTH_USER_MODEL),
        ),
    ]
