# Generated by Django 4.0.2 on 2022-02-25 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_hashtag_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='hashtag',
            field=models.ManyToManyField(related_name='followtag', to=settings.AUTH_USER_MODEL),
        ),
    ]
