# Generated by Django 4.0.2 on 2022-02-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_follow_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='hashtag',
            field=models.ManyToManyField(related_name='followtag', to='api.Hashtag'),
        ),
    ]
