# Generated by Django 4.0.2 on 2022-02-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_follow_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='hashtag',
        ),
    ]
