# Generated by Django 4.0.2 on 2022-02-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_hashtag_follower_tagfollow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagFollow',
        ),
    ]
