# Generated by Django 4.0.2 on 2022-02-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_tagfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagfollow',
            name='checkunique',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
