# Generated by Django 4.0.2 on 2022-02-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_tagfollow_checkunique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupname',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupName',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
