# Generated by Django 4.0.2 on 2022-03-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='post_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
