# Generated by Django 4.0.2 on 2022-02-28 14:45

from django.conf import settings
from django.db import migrations, models
import hashtag.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('name', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('username', models.ForeignKey(null=True, on_delete=hashtag.models.superuser, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkunique', models.CharField(max_length=16, unique=True)),
                ('follower', models.ManyToManyField(null=True, related_name='tag_follower_name', to=settings.AUTH_USER_MODEL)),
                ('name', models.ManyToManyField(null=True, related_name='tag_name', to='hashtag.Hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(null=True, on_delete=hashtag.models.superuser, related_name='followed_by', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(null=True, on_delete=hashtag.models.superuser, related_name='follow_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
