# Generated by Django 4.0.2 on 2022-03-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0002_alter_tagfollow_checkunique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
